### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by slychief** [dmcennis/jAudioGIT#7]
Hello!

I would like to use jAudio in a funded project. May I ask you to add a license to your repository, please? Is it the same as provided on sourcforge => GNU Library or Lesser General Public License version 2.0 (LGPLv2), GNU General Public License version 2.0 (GPLv2) ?

Thanks,
Alex

**Comment by dmcennis** [comment]
jAudio itself is LGPL 2.1. jMir uses Weka and others, resulting in GPL licenses for jMir as a whole. A License.txt has been added to jAudio to make this explicit. Thanks for the heads up.

**Comment by dmcennis** [comment]
I should comment that I am available for consulting connected to this project and accept contributions to prioritize jAudio development.
